name: genre_classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - protobuf=3.13.0
  - requests=2.24.0
  - numpy=1.19.5
  - mlflow=1.14.1
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - pip=20.3.3
  - pip:
      - wandb==0.10.31
